stages:
- name: Build
  steps:
  - runScriptConfig:
      image: php:7
      shellScript: |-
        apt update
        apt install -y wget git zip unzip
        wget https://getcomposer.org/installer
        php installer
        php composer.phar install
        make lint
        make test
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: agent-pilotorder:${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_COMMIT}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
  when:
    branch:
      include:
      - master
notification: {}
